### ISSUE TITLE
Document requirements and send them to validate

### ISSUE THREAD

**Issue by linusbrown47** [GoldmanDAO/fluidity#20]

**Comment by xPi2** [comment]
Waiting for #1

**Comment by xPi2** [comment]
Documented and sent functional requirements in regards to:
1. LQTY initial distribution
2. Frontend operators
3. Protocol base parameters (periods, rates)

**Comment by xPi2** [comment]
I don't think we can expect a proper UI spec so when we have a version of the frontend with which we are ok we send it and wait for feedback and requests. Closing this for the time being.
