### ISSUE TITLE
Check why tests are failing

### ISSUE THREAD

**Issue by linusbrown47** [GoldmanDAO/fluidity#22]

**Comment by EnriqCG** [comment]
Test run successfully with the current state of the repo. I run into several issues with the set up though, which mainly include having to run a local OpenEtereum container for E2E tests to run. This was not stated on the README and I would add it as an improvement that we can make to the docs. (Running `yarn start-dev-chain` is enough to get it working).

Once all prerequisites have been met, tests run on the different workspaces testing the multiple Liquity libraries.

Some error logging does appear (I believe this is what @xPi2 was seeing originally - please confirm) but these are errors expected by the testing suite itself and errors that are related to external dependencies. See image below for a failed request to Uniswap:
![image](https://user-images.githubusercontent.com/38569176/158264415-6c89de4b-ca20-4c2f-8951-ee7c0fe87d72.png)

The `fetchLqtyPrice` function is failing on a request to api.thegraph.org.
https://github.com/GoldmanDAO/fluidity/blob/d97ca8c9fc378c94b8393d8880efd1193cd48aa8/packages/dev-frontend/src/components/Stability/Yield.tsx#L30

A few other errors do show but after checking the source code as well those errors are always catched but they just happened to be followed by a `console.error()`. So I would not count this as tests not working, just that the code is "failing", console logging and passing the test.

All these errors does not prevent tests from completing succesfully.
