### ISSUE TITLE
UI Component to show the stats on the top

### ISSUE THREAD

**Issue by linusbrown47** [GoldmanDAO/fluidity#29]
Should be able to show and hide which stats to show in each page

**Comment by xPi2** [comment]
I've modified the SystemStats component to be able to filter specific stats through the `filterStats` prop.
Current filterable stats:
- `borrow-fee`: Borrowing fee
- `redeem-fee`: Redemption fee
- `tvl`: Total value locked
- `troves`: Number of active troves
- `lusd-supply`: Total LUSD minted
- `lusd-sp`: LUSD in Stability Pool
- `staked-lqty`: Total amount of LQTY staked
- `tcr`: Total Collateral Ratio
- `recovery`: Recovery mode indicator

**Comment by xPi2** [comment]
I've added `showBalances`, `showProtocol` & `showPriceFeed` for eve more modularity:

- `showBalances`: Render balance stats section
- `showProtocol`: Render protocol stats section
- `showPriceFeed`: Render price feed section

With this stats module can be fully configurable to show independent sections on different components or mix them as needed.
