### ISSUE TITLE
Get frontend running in Vercel / GH Pages

### ISSUE THREAD

**Issue by linusbrown47** [GoldmanDAO/fluidity#3]
Pls, document anything related with environment variables

**Comment by HornyTofu** [comment]
There are two environment variables in the project: `FRONTEND_TAG` and `INFURA_API_KEY`
Both are optional. Do we plan to use them?

From [README](https://github.com/GoldmanDAO/fluidity#configuring-a-public-frontend):

> **FRONTEND_TAG**
If you want to receive a share of the LQTY rewards earned by users of your frontend, set this variable to the Ethereum address you want the LQTY to be sent to.
>
> **INFURA_API_KEY**
This is an optional parameter. If you'd like your frontend to use Infura's [WebSocket endpoint](https://infura.io/docs/ethereum#section/Websockets) for receiving blockchain events, set this variable to an Infura Project ID.

**Comment by linusbrown47** [comment]
We won't be using any of them, good questions tho.
FRONTEND_TAG: Frontend will be run by the client, not us. So not use for this.
INFURA_API_KEY: Even if we wanted to, infura won't be supporting the chain we are going to launch on, so no use for this.
