### ISSUE TITLE
Make frontend run with initial contracts

### ISSUE THREAD

**Issue by linusbrown47** [GoldmanDAO/fluidity#5]

**Comment by xPi2** [comment]
Done, if you follow the README is pretty much out of the box.

**Requirements:**

- Yarn
- Node v12.x
- Docker

1. Start / stop local node with:

```bash
yarn start-dev-chain
yarn stop-dev-chain
```

This will run an OpenEthereum docker image with all the contracts deployed.

**!**Remember to check that ChainID on the log matches Metamask ChainID.

2. Start the frontend with:

```bash
yarn start-dev-frontend
```

3. Select localhost network in Metamask

In case it's not automatically configured:
- RPC's URL: http://localhost:8545
- ChainID: 17
- Symbol: ETH

4. Import Scrooge McDuck account

Import account from private key for infinite money:
`0x4d5db4107d237df6a3d58ee5f70ae63d73d7658d4026f2eefd2f204c81682cb7`
